### ISSUE TITLE
Dealing with big export

### ISSUE THREAD

**Issue by SylvanoTombo** [FriendsOfSylius/SyliusImportExportPlugin#258] opened 2021-03-29 10:36 UTC
Hello There, is there a way to deal with big export?

When i export large data, i have 504 gateway time out from nginx

**Comment by tuala** [comment] 2021-07-21 10:29
This plugin is lackluster at best, it is barely maintained and has no built in way to deal with big export from UI. I'd advice to write your own using message queues, it will be faster than spending hours trying to figure out all that is wrong with this and trying to customize it.

**Comment by oallain** [comment] 2021-07-27 12:03
Duplicate of https://github.com/FriendsOfSylius/SyliusImportExportPlugin/issues/224

**Closed by oallain** 2021-07-27 12:03 UTC
